SELECT * 
FROM customer_behaviour;

--QUESTION 1: WHAT IS THE TOTAL REVENUE GENERATED BY MALE VS FEMALE CUSTOMERS?
SELECT 
	gender,
	SUM(purchase_amount) AS revenue
FROM customer_behaviour
GROUP BY gender;

---QUESTION 2: WHICH CUSTOMERS USED A DISCOUNT BUT STILL SPENT MORE THAN THE AVERAGE PURCHASE AMOUNT?
SELECT 
	customer_id,
	purchase_amount
FROM customer_behaviour
WHERE discount_applied='Yes' and purchase_amount >=(
		SELECT AVG(purchase_amount)
		FROM customer_behaviour);	

---QUESTION 3: WHICH ARE THE TOP 5 PRODUCTS WITH THE HIGHEST AVERAGE REVIEW RATING?
SELECT
	item_purchased,
	ROUND(AVG(review_rating):: NUMERIC,2) AS "Average Product Rating"
FROM customer_behaviour
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

---QUESTION 4: COMPARE THE AVERAGE PURCHASE AMOUNTS BETWEEN STANDARD AND EXPRESS SHIPPING
SELECT 
shipping_type,
ROUND(AVG(purchase_amount),2)
FROM customer_behaviour
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

---QUESTION 5: DO SUBSCRIBED CUSTOMERS SPEND MORE MONEY? 
---COMPARE AVERAGE SPEND AND TOTAL REVENUE BETWEEN SUBSCRIBERS AND NON-SUBSCRIBERS
SELECT 
	subscription_status,
	COUNT(customer_id) AS total_customers,
	ROUND(AVG(purchase_amount),2) AS avg_spend,
	ROUND(SUM(purchase_amount),2) AS total_revenue
FROM customer_behaviour
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

---QUESTION 6: WHICH 5 PRODUCTS HAVE HIGHEST PERCENTAGE OF PURCHASE WITH DISCOUNTS APPLIED?
SELECT
	item_purchased,
	ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM customer_behaviour
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

---QUESTION 7: SEGEMENT CUSTOMERS into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
WITH customer_type as (
SELECT 
	customer_id, 
	previous_purchases,
	CASE 
    	WHEN previous_purchases = 1 THEN 'New'
    	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    	ELSE 'Loyal'
    	END AS customer_segment
FROM customer_behaviour)

SELECT 
	customer_segment,count(*) AS "Number of Customers" 
FROM customer_type 
GROUP BY customer_segment;

--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_behaviour
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
 
--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM customer_behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_behaviour
GROUP BY age_group
ORDER BY total_revenue desc;

	